name: Testes Automatizados

on:
  push:
    branches:
      - development
      - staging
  pull_request:
    branches:
      - development
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar os testes
        run: pytest --maxfail=1 --disable-warnings
